eSISVISA/SISVISA.UI.Web/Controllers/TermoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SISVISA.Core.Regra;
using SISVISA.Core.Models;
using SISVISA.Core.Response;

namespace SISVISA.UI.Web.Controllers
{
    public class TermoController : Controller
    {
        private TermoRegra _regra = new TermoRegra();
        // GET: Termo
        public ActionResult Index()
        {            
            return View(_regra.ListarTermos());
        }

        // GET: Termo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Termo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Termo obj)
        {
            if (ModelState.IsValid)
            {
                Termo retorno = new Termo();
                retorno = _regra.IncluirTermo(obj);
                if (retorno.status.Equals(ResponseStatus.SUCESSO.Texto))
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, retorno.mensagem);
            }

            return View(obj);
        }

        // GET: Termo/Edit/5
        public ActionResult Edit(int id)
        {

            return View(_regra.ListarTermos().Where(x => x.cod_termo == id).FirstOrDefault());
        }

        // POST: Termo/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Termo obj)
        {            
            if (ModelState.IsValid)
            {
                Termo retorno = new Termo();
                retorno = _regra.AlterarTermo(obj);
                if (retorno.status.Equals(ResponseStatus.SUCESSO.Texto))
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, retorno.mensagem);
            }            
            return View(obj);
        }
    }
}

eSISVISA/SISVISA.UI.Web/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SISVISA.Core.Regra;
using SISVISA.Core.Models;
using SISVISA.Core.Response;

namespace SISVISA.UI.Web.Controllers
{
    public class UsuarioController : Controller
    {
        private UsuarioRegra _regra = new UsuarioRegra();
        // GET: Usuario
        public ActionResult Index()
        {            
            return View(_regra.ListarUsuarios());
        }

        // GET: Usuario/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Usuario obj)
        {
            if (ModelState.IsValid)
            {
                Usuario retorno = new Usuario();
                retorno = _regra.IncluirUsuario(obj);
                if (retorno.status.Equals(ResponseStatus.SUCESSO.Texto))
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, retorno.mensagem);
            }

            return View(obj);
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int id)
        {

            return View(_regra.ListarUsuarios().Where(x => x.cod_usuario == id).FirstOrDefault());
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usuario obj)
        {            
            if (ModelState.IsValid || obj.txt_senha == null)
            {
                Usuario retorno = new Usuario();
                retorno = _regra.AlterarUsuario(obj);
                if (retorno.status.Equals(ResponseStatus.SUCESSO.Texto))
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, retorno.mensagem);
            }            
            return View(obj);
        }
    }
}

eSISVISA/SISVISA.UI.Web/Views/Termo/Create.cshtml
@model SISVISA.Core.Models.Usuario

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Usuário</h3>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-horizontal box-body">
            <div class="form-group">
                @Html.LabelFor(model => model.txt_usuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.txt_usuario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.txt_usuario, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.txt_email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.txt_email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.txt_email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.txt_login, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.txt_login, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.txt_login, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.txt_senha, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.txt_senha, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.txt_senha, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.cod_ativo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.cod_ativo)
                        @Html.ValidationMessageFor(model => model.cod_ativo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="col-md-offset-1 col-md-6">
                    <input type="submit" value="Incluir" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>            
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

eSISVISA/SISVISA.UI.Web/Views/Termo/Edit.cshtml
@model SISVISA.Core.Models.Usuario

@using (Html.BeginForm("Edit", "Usuario", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Usuário</h3>
        </div>        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.cod_usuario)
        <div class="form-horizontal box-body">
            <div class="form-group">
                @Html.LabelFor(model => model.txt_usuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.txt_usuario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.txt_usuario, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.txt_email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.txt_email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.txt_email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.txt_login, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.txt_login, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.txt_login, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.cod_ativo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.cod_ativo)
                        @Html.ValidationMessageFor(model => model.cod_ativo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <div class="col-md-offset-1 col-md-6">
                    <input type="submit" value="Salvar" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </div>            
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

eSISVISA/SISVISA.UI.Web/Views/Termo/Index.cshtml
@model IEnumerable<SISVISA.Core.Models.Termo>

<section class="content-header">
    <h1>Usuários</h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Configuração</a></li>
        <li><a href="@Url.Action("Index", "Termo")">Termos</a></li>
        <li class="active">Listagem</li>
    </ol>
</section><br />
<div class="box">
    <div class="box-header">
        <h3 class="box-title">@Html.ActionLink("Incluir", "Create")</h3>        
    </div>
    <div class="box-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>                    
                    <th>@Html.DisplayNameFor(model => model.txt_sigla)</th>
                    <th>@Html.DisplayNameFor(model => model.txt_descricao)</th>
                    <th>@Html.DisplayNameFor(model => model.txt_observacao)</th>
                    <th>@Html.DisplayNameFor(model => model.cod_ativo)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>                        
                        <td>@Html.DisplayFor(modelItem => item.txt_sigla)</td>
                        <td>@Html.DisplayFor(modelItem => item.txt_descricao)</td>
                        <td>@Html.DisplayFor(modelItem => item.txt_observacao)</td>
                        <td>@Html.DisplayFor(modelItem => item.cod_ativo)</td>
                        <td>                            
                            <a href="@Url.Action("Edit", "Termo", new { id = item.cod_termo })" class="btn btn-primary btn-xs">Alterar</a>
                        </td>
                    </tr>
                }                
            </tbody>
        </table>
    </div>
</div>